// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DTO;
using Entities;
namespace IService
{
	public interface IUserOrdersService
	{		
        UserOrdersDTO Add(UserOrdersDTO userorders);
        void Delete(int UserOrdersID);
        void Renew(UserOrdersDTO userorders);
        UserOrdersDTO Get(int UserOrdersID);
        IList<UserOrdersDTO> GetList();
    }
}
