//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlServerContainer : DbContext
    {
        public SqlServerContainer()
            : base("name=SqlServerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_Products> T_Products { get; set; }
        public DbSet<T_Fruits> T_Fruits { get; set; }
        public DbSet<T_UserOrders> T_ProductOrder { get; set; }
        public DbSet<T_ProductOrders> T_ProductOrders { get; set; }
        public DbSet<T_Place> T_Place { get; set; }
        public DbSet<T_PostAddress> T_PostAddress { get; set; }
        public DbSet<C_ProductFruits> C_ProductFruitS { get; set; }
        public DbSet<T_Inventory> T_Inventory { get; set; }
        public DbSet<T_Stockin> T_Warehousing { get; set; }
        public DbSet<T_Storage> T_Storage { get; set; }
        public DbSet<T_Supplier> T_Supplier { get; set; }
        public DbSet<T_SupplierFruit> T_SupplierFruit { get; set; }
        public DbSet<T_Manager> T_Manager { get; set; }
        public DbSet<T_Permission> T_Permission { get; set; }
        public DbSet<T_ManagerPermission> T_ManagerPermission { get; set; }
        public DbSet<T_ProductPic> T_ProductPic { get; set; }
        public DbSet<T_FruitPic> T_FruitPic { get; set; }
    }
}
