//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlServerContainer : DbContext
    {
        public SqlServerContainer()
            : base("name=SqlServerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_Products> T_Products { get; set; }
        public DbSet<T_Fruits> T_Fruits { get; set; }
        public DbSet<T_PostAddress> T_PostAddress { get; set; }
        public DbSet<T_UserOrders> T_ProductOrder { get; set; }
        public DbSet<T_ProductOrders> T_ProductOrders { get; set; }
        public DbSet<T_Place> T_Place { get; set; }
    }
}
