//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fruits
    {
        public T_Fruits()
        {
            this.Enabled = true;
            this.C_ProductFruits = new HashSet<C_ProductFruits>();
            this.T_Warehousing = new HashSet<T_Stockin>();
            this.T_Inventory = new HashSet<T_Inventory>();
            this.T_Storage = new HashSet<T_Storage>();
            this.T_SupplierFruit = new HashSet<T_SupplierFruit>();
        }
    
        public int FruitID { get; set; }
        public string FruitName { get; set; }
        public string HowToEat { get; set; }
        public string Detail { get; set; }
        public byte ProductSeason { get; set; }
        public int PlaceID { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<C_ProductFruits> C_ProductFruits { get; set; }
        public virtual ICollection<T_Stockin> T_Warehousing { get; set; }
        public virtual ICollection<T_Inventory> T_Inventory { get; set; }
        public virtual ICollection<T_Storage> T_Storage { get; set; }
        public virtual ICollection<T_SupplierFruit> T_SupplierFruit { get; set; }
    }
}
