//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fruits
    {
        public int FruitID { get; set; }
        public string FruitName { get; set; }
        public string HowToEat { get; set; }
        public string Detail { get; set; }
        public byte ProductSeason { get; set; }
    
        public virtual T_Products T_Products { get; set; }
    }
}
