//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManagerPermission
    {
        public T_ManagerPermission()
        {
            this.Enabled = true;
            this.Permission = 1;
        }
    
        public int ManagerPermissionID { get; set; }
        public int ManagerID { get; set; }
        public int PermissionID { get; set; }
        public bool Enabled { get; set; }
        public byte Permission { get; set; }
    
        public virtual T_Permission T_Permission { get; set; }
        public virtual T_Manager T_Manager { get; set; }
    }
}
