//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Permission
    {
        public T_Permission()
        {
            this.Enabled = true;
            this.T_ManagerPermission = new HashSet<T_ManagerPermission>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionName { get; set; }
        public string PermissionNum { get; set; }
        public string ParentNum { get; set; }
        public byte PermissionType { get; set; }
        public string PermissionUrl { get; set; }
        public string PermissionAction { get; set; }
        public string PermissionStyle { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<T_ManagerPermission> T_ManagerPermission { get; set; }
    }
}
