//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PostAddress
    {
        public T_PostAddress()
        {
            this.Enabled = true;
        }
    
        public int PostAddressID { get; set; }
        public string Address { get; set; }
        public bool IsDefault { get; set; }
        public string Phone { get; set; }
        public string ContentName { get; set; }
        public string Tel { get; set; }
        public string Detail { get; set; }
        public int UserID { get; set; }
        public int PlaceID { get; set; }
        public bool Enabled { get; set; }
    
        public virtual T_User T_User { get; set; }
    }
}
