//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Products
    {
        public T_Products()
        {
            this.Enabled = true;
            this.C_ProductFruitS = new HashSet<C_ProductFruits>();
        }
    
        public int ProductID { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal SalePrice { get; set; }
        public int SalesVolume { get; set; }
        public bool Enabled { get; set; }
        public string ProductName { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<C_ProductFruits> C_ProductFruitS { get; set; }
    }
}
