//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Products
    {
        public T_Products()
        {
            this.T_Fruits = new HashSet<T_Fruits>();
            this.T_ProductOrders = new HashSet<T_ProductOrders>();
        }
    
        public int ProductID { get; set; }
        public string OriginalPrice { get; set; }
        public string SalePrice { get; set; }
        public string SalesVolume { get; set; }
    
        public virtual ICollection<T_Fruits> T_Fruits { get; set; }
        public virtual ICollection<T_ProductOrders> T_ProductOrders { get; set; }
    }
}
