//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductPic
    {
        public int ProductPicID { get; set; }
        public string PicURL { get; set; }
        public string ThumbPicURL { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int ProductID { get; set; }
    
        public virtual T_Products T_Products { get; set; }
    }
}
