//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Supplier
    {
        public T_Supplier()
        {
            this.Enabled = true;
            this.T_SupplierFruit = new HashSet<T_SupplierFruit>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Contacts { get; set; }
        public string Detail { get; set; }
        public bool Enabled { get; set; }
        public int PlaceID { get; set; }
    
        public virtual ICollection<T_SupplierFruit> T_SupplierFruit { get; set; }
    }
}
