//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserOrders
    {
        public T_UserOrders()
        {
            this.Enabled = true;
            this.T_ProductOrders = new HashSet<T_ProductOrders>();
        }
    
        public int UserOrdersID { get; set; }
        public System.DateTime DateCreate { get; set; }
        public decimal Amount { get; set; }
        public decimal SaleAmount { get; set; }
        public byte OrderStatus { get; set; }
        public string LogisticsNum { get; set; }
        public System.DateTime DatePay { get; set; }
        public System.DateTime DateConfirm { get; set; }
        public int UserID { get; set; }
        public bool Enabled { get; set; }
        public decimal postage { get; set; }
    
        public virtual T_User T_User { get; set; }
        public virtual ICollection<T_ProductOrders> T_ProductOrders { get; set; }
    }
}
