//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMould
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserOrders
    {
        public T_UserOrders()
        {
            this.T_ProductOrders = new HashSet<T_ProductOrders>();
        }
    
        public int T_UserOrdersID { get; set; }
        public string DateCreate { get; set; }
        public string Amount { get; set; }
        public string SaleAmount { get; set; }
        public string OrderStatus { get; set; }
        public string LogisticsNum { get; set; }
        public string DatePay { get; set; }
        public string DateConfirm { get; set; }
    
        public virtual T_User T_User { get; set; }
        public virtual ICollection<T_ProductOrders> T_ProductOrders { get; set; }
    }
}
