// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_Fruits
    /// </summary>
	public class T_Fruits
	{
		public T_Fruits()
		{
			this.Enabled = true;
			this.C_ProductFruits = new HashSet<C_ProductFruits>();
			this.T_Warehousing = new HashSet<T_Stockin>();
			this.T_Inventory = new HashSet<T_Inventory>();
			this.T_Storage = new HashSet<T_Storage>();
			this.T_SupplierFruit = new HashSet<T_SupplierFruit>();
		}		
        /// <summary>
        /// 水果ID
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int FruitID { get; set; }
        /// <summary>
        /// 水果名称
        /// </summary>
    
        [MaxLength(200)]
        [Required(ErrorMessage="值不能为空")]
		public string FruitName { get; set; }
        /// <summary>
        /// 食用方式
        /// </summary>
    
        [MaxLength(200)]
		public string HowToEat { get; set; }
        /// <summary>
        /// 详细说明
        /// </summary>
    
        [MaxLength(4000)]
		public string Detail { get; set; }
        /// <summary>
        /// 产时
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public byte ProductSeason { get; set; }
        /// <summary>
        /// 产地
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int PlaceID { get; set; }
        /// <summary>
        /// 有效
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<C_ProductFruits> C_ProductFruits { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_Stockin> T_Warehousing { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_Inventory> T_Inventory { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_Storage> T_Storage { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_SupplierFruit> T_SupplierFruit { get; set; }
		
	}
}
