// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
    /// <summary>
    /// T_Inventory
    /// </summary>
	public class T_Inventory
	{
        /// <summary>
        /// 
        /// </summary>
		public int InventoryID { get; set; }
        /// <summary>
        /// 
        /// </summary>
		public int Count { get; set; }
        /// <summary>
        /// 
        /// </summary>
		public int FruitID { get; set; }
        /// <summary>
        /// 
        /// </summary>
		public int StorageID { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_Fruits T_Fruits { get; set; }
		
	}
}
