// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_ManagerPermission
    /// </summary>
	public class T_ManagerPermission
	{
		public T_ManagerPermission()
		{
			this.Enabled = true;
			this.Permission = 1;
		}		
        /// <summary>
        /// 
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int ManagerPermissionID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int ManagerID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int PermissionID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public byte Permission { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_Permission T_Permission { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_Manager T_Manager { get; set; }
		
	}
}
