// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
	public class T_ProductOrders
	{
		public int ProductOrdersID { get; set; }
		public int Count { get; set; }
		public int UserOrdersID { get; set; }
		public int ProductID { get; set; }
		public virtual T_UserOrders T_UserOrders { get; set; }
		
	}
}
