// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
	public class T_Products
	{
		public T_Products()
		{
			this.Enabled = true;
			this.C_ProductFruitS = new HashSet<C_ProductFruits>();
		}		
		public int ProductID { get; set; }
		public decimal OriginalPrice { get; set; }
		public decimal SalePrice { get; set; }
		public int SalesVolume { get; set; }
		public bool Enabled { get; set; }
		public virtual ICollection<C_ProductFruits> C_ProductFruitS { get; set; }
		
	}
}
