// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_Products
    /// </summary>
	public class T_Products
	{
		public T_Products()
		{
			this.Enabled = true;
			this.C_ProductFruitS = new HashSet<C_ProductFruits>();
			this.T_ProductPic = new HashSet<T_ProductPic>();
		}		
        /// <summary>
        /// 产品ID
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int ProductID { get; set; }
        /// <summary>
        /// 产品原价
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public decimal OriginalPrice { get; set; }
        /// <summary>
        /// 产品折扣价
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public decimal SalePrice { get; set; }
        /// <summary>
        /// 销售总数
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int SalesVolume { get; set; }
        /// <summary>
        /// 有效无效
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 产品名称
        /// </summary>
    
        [MaxLength()]
        [Required(ErrorMessage="值不能为空")]
		public string ProductName { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength()]
        [Required(ErrorMessage="值不能为空")]
		public string Detail { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<C_ProductFruits> C_ProductFruitS { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_ProductPic> T_ProductPic { get; set; }
		
	}
}
