// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
	public class T_Stockin
	{
		public int StockinID { get; set; }
		public string FruitID { get; set; }
		public decimal count { get; set; }
		public System.DateTime datecreate { get; set; }
		public string StorageID { get; set; }
		public int PlaceID { get; set; }
		public string DeliverAddress { get; set; }
		public System.DateTime dateStockin { get; set; }
		public string status { get; set; }
		public Nullable<int> SupplierID { get; set; }
		public virtual T_Fruits T_Fruits { get; set; }
		
	}
}
