// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_Storage
    /// </summary>
	public class T_Storage
	{
		public T_Storage()
		{
			this.Enabled = true;
		}		
        /// <summary>
        /// 
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int StorageID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int PlaceID { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(500)]
		public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int FruitID { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_Fruits T_Fruits { get; set; }
		
	}
}
