// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
	public class T_SupplierFruit
	{
		public T_SupplierFruit()
		{
			this.Enabled = true;
		}		
		public int SupplierFruitID { get; set; }
		public int FruitID { get; set; }
		public bool Enabled { get; set; }
		public virtual T_Supplier T_Supplier { get; set; }
		
	}
}
