// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace Entities
{
    /// <summary>
    /// T_SupplierFruit
    /// </summary>
	public class T_SupplierFruit
	{
		public T_SupplierFruit()
		{
			this.Enabled = true;
		}		
        /// <summary>
        /// 
        /// </summary>
		public int SupplierFruitID { get; set; }
        /// <summary>
        /// 
        /// </summary>
		public int FruitID { get; set; }
        /// <summary>
        /// 
        /// </summary>
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_Supplier T_Supplier { get; set; }
		
	}
}
