// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_Supplier
    /// </summary>
	public class T_Supplier
	{
		public T_Supplier()
		{
			this.Enabled = true;
			this.T_SupplierFruit = new HashSet<T_SupplierFruit>();
		}		
        /// <summary>
        /// 
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int SupplierID { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(200)]
        [Required(ErrorMessage="值不能为空")]
		public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(500)]
		public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(50)]
		public string Tel { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(50)]
        [Required(ErrorMessage="值不能为空")]
		public string Phone { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(50)]
        [Required(ErrorMessage="值不能为空")]
		public string Contacts { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength(500)]
		public string Detail { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int PlaceID { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_SupplierFruit> T_SupplierFruit { get; set; }
		
	}
}
