// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Entities
{
    /// <summary>
    /// T_UserOrders
    /// </summary>
	public class T_UserOrders
	{
		public T_UserOrders()
		{
			this.Enabled = true;
			this.T_ProductOrders = new HashSet<T_ProductOrders>();
		}		
        /// <summary>
        /// 
        /// </summary>
        [Key]               
        [Required(ErrorMessage="值不能为空")]
		public int UserOrdersID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public System.DateTime DateCreate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public decimal Amount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public decimal SaleAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public byte OrderStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        [MaxLength()]
        [Required(ErrorMessage="值不能为空")]
		public string LogisticsNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public System.DateTime DatePay { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public System.DateTime DateConfirm { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public int UserID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage="值不能为空")]
		public decimal postage { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual T_User T_User { get; set; }
        /// <summary>
        /// 
        /// </summary>

		public virtual ICollection<T_ProductOrders> T_ProductOrders { get; set; }
		
	}
}
