// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class InventoryService: ServiceBase, IInventoryService
	{		
  
        private IBaseDao _dal;

        public InventoryService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public InventoryDTO Add(InventoryDTO inventory)
        { 
           
            T_Inventory FruitResult = _dal.Insert<T_Inventory>(Mapper.Map<T_Inventory>(inventory));            
            return Mapper.Map<InventoryDTO>(FruitResult);
        }
        public void Delete(int InventoryID)
        {
            _dal.Delete<T_Inventory>(new T_Inventory { InventoryID = InventoryID }, true);
        }
        public void Renew(InventoryDTO inventory)
        {
           
            _dal.Update<T_Inventory>(Mapper.Map<T_Inventory>(inventory),true);
        }
        public InventoryDTO Get(int InventoryID)
        {
           
            return Mapper.Map<InventoryDTO>(_dal.GetEntityByID<T_Inventory>(InventoryID));
        }
        public IList<InventoryDTO> GetList()
        {
            
            return _dal.GetEntities<T_Inventory>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_Inventory, InventoryDTO>()).ToList();  
        }
    }
}
