// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class PlaceService: ServiceBase, IPlaceService
	{		
  
        private IBaseDao _dal;

        public PlaceService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public PlaceDTO Add(PlaceDTO place)
        { 
           
            T_Place FruitResult = _dal.Insert<T_Place>(Mapper.Map<T_Place>(place));            
            return Mapper.Map<PlaceDTO>(FruitResult);
        }
        public void Delete(int PlaceID)
        {
            _dal.Update<T_Place>(new T_Place { Enabled = false }, true);
        }
        public void Renew(PlaceDTO place)
        {
           
            _dal.Update<T_Place>(Mapper.Map<T_Place>(place),true);
        }
        public PlaceDTO Get(int PlaceID)
        {
           
            return Mapper.Map<PlaceDTO>(_dal.GetEntityByID<T_Place>(PlaceID));
        }
        public IList<PlaceDTO> GetList()
        {
            
            return _dal.GetEntities<T_Place>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_Place, PlaceDTO>()).ToList();  
        }
    }
}
