// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class PostAddressService: ServiceBase, IPostAddressService
	{		
  
        private IBaseDao _dal;

        public PostAddressService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public PostAddressDTO Add(PostAddressDTO postaddress)
        { 
           
            T_PostAddress FruitResult = _dal.Insert<T_PostAddress>(Mapper.Map<T_PostAddress>(postaddress));            
            return Mapper.Map<PostAddressDTO>(FruitResult);
        }
        public void Delete(int PostAddressID)
        {
            _dal.Update<T_PostAddress>(new T_PostAddress { Enabled = false }, true);
        }
        public void Renew(PostAddressDTO postaddress)
        {
           
            _dal.Update<T_PostAddress>(Mapper.Map<T_PostAddress>(postaddress),true);
        }
        public PostAddressDTO Get(int PostAddressID)
        {
           
            return Mapper.Map<PostAddressDTO>(_dal.GetEntityByID<T_PostAddress>(PostAddressID));
        }
        public IList<PostAddressDTO> GetList()
        {
            
            return _dal.GetEntities<T_PostAddress>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_PostAddress, PostAddressDTO>()).ToList();  
        }
    }
}
