// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class ProductsService: ServiceBase, IProductsService
	{		
  
        private IBaseDao _dal;

        public ProductsService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public ProductsDTO Add(ProductsDTO products)
        { 
           
            T_Products FruitResult = _dal.Insert<T_Products>(Mapper.Map<T_Products>(products));            
            return Mapper.Map<ProductsDTO>(FruitResult);
        }
        public void Delete(int ProductsID)
        {
            _dal.Update<T_Products>(new T_Products { Enabled = false }, true);
        }
        public void Renew(ProductsDTO products)
        {
           
            _dal.Update<T_Products>(Mapper.Map<T_Products>(products),true);
        }
        public ProductsDTO Get(int ProductsID)
        {
           
            return Mapper.Map<ProductsDTO>(_dal.GetEntityByID<T_Products>(ProductsID));
        }
        public IList<ProductsDTO> GetList()
        {
            
            return _dal.GetEntities<T_Products>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_Products, ProductsDTO>()).ToList();  
        }
    }
}
