// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class StockinService: ServiceBase, IStockinService
	{		
  
        private IBaseDao _dal;

        public StockinService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public StockinDTO Add(StockinDTO stockin)
        { 
           
            T_Stockin FruitResult = _dal.Insert<T_Stockin>(Mapper.Map<T_Stockin>(stockin));            
            return Mapper.Map<StockinDTO>(FruitResult);
        }
        public void Delete(int StockinID)
        {
            _dal.Delete<T_Stockin>(new T_Stockin { StockinID = StockinID }, true);
        }
        public void Renew(StockinDTO stockin)
        {
           
            _dal.Update<T_Stockin>(Mapper.Map<T_Stockin>(stockin),true);
        }
        public StockinDTO Get(int StockinID)
        {
           
            return Mapper.Map<StockinDTO>(_dal.GetEntityByID<T_Stockin>(StockinID));
        }
        public IList<StockinDTO> GetList()
        {
            
            return _dal.GetEntities<T_Stockin>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_Stockin, StockinDTO>()).ToList();  
        }
    }
}
