// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class StorageService: ServiceBase, IStorageService
	{		
  
        private IBaseDao _dal;

        public StorageService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public StorageDTO Add(StorageDTO storage)
        { 
           
            T_Storage FruitResult = _dal.Insert<T_Storage>(Mapper.Map<T_Storage>(storage));            
            return Mapper.Map<StorageDTO>(FruitResult);
        }
        public void Delete(int StorageID)
        {
            _dal.Update<T_Storage>(new T_Storage { Enabled = false }, true);
        }
        public void Renew(StorageDTO storage)
        {
           
            _dal.Update<T_Storage>(Mapper.Map<T_Storage>(storage),true);
        }
        public StorageDTO Get(int StorageID)
        {
           
            return Mapper.Map<StorageDTO>(_dal.GetEntityByID<T_Storage>(StorageID));
        }
        public IList<StorageDTO> GetList()
        {
            
            return _dal.GetEntities<T_Storage>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_Storage, StorageDTO>()).ToList();  
        }
    }
}
