// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IService;
using DTO;
using Entities;
using IDAL;
using Common;
namespace Service
{
	public class SupplierFruitService: ServiceBase, ISupplierFruitService
	{		
  
        private IBaseDao _dal;

        public SupplierFruitService(IBaseDao dal)            
        {
            _dal = dal;
            

        }
        public SupplierFruitDTO Add(SupplierFruitDTO supplierfruit)
        { 
           
            T_SupplierFruit FruitResult = _dal.Insert<T_SupplierFruit>(Mapper.Map<T_SupplierFruit>(supplierfruit));            
            return Mapper.Map<SupplierFruitDTO>(FruitResult);
        }
        public void Delete(int SupplierFruitID)
        {
            _dal.Update<T_SupplierFruit>(new T_SupplierFruit { Enabled = false }, true);
        }
        public void Renew(SupplierFruitDTO supplierfruit)
        {
           
            _dal.Update<T_SupplierFruit>(Mapper.Map<T_SupplierFruit>(supplierfruit),true);
        }
        public SupplierFruitDTO Get(int SupplierFruitID)
        {
           
            return Mapper.Map<SupplierFruitDTO>(_dal.GetEntityByID<T_SupplierFruit>(SupplierFruitID));
        }
        public IList<SupplierFruitDTO> GetList()
        {
            
            return _dal.GetEntities<T_SupplierFruit>(m => 1 == 1, true).Select(CreateDataMapper.GetMappedSelector<T_SupplierFruit, SupplierFruitDTO>()).ToList();  
        }
    }
}
