// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class FruitPicSeed
	{		
  
        public T_FruitPic GetEntitySeed()
        {
            return new T_FruitPic
                        {
                            FruitPicID=RandomData.GetRandomInt(1,100),
                            PicURL="",
                            ThumbPicURL="",
                            DateCreate=RandomData.GetRadomTime(),
                            FruitID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
        public FruitPicDTO GetDTOSeed()
        {
            return new FruitPicDTO
                        {
                            FruitPicID=RandomData.GetRandomInt(1,100),
                            PicURL="",
                            ThumbPicURL="",
                            DateCreate=RandomData.GetRadomTime(),
                            FruitID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
    }
}
