// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
namespace DataSeeds
{
	public class FruitsSeed
	{		
  
        public T_Fruits GetEntitySeed()
        {
            return new T_Fruits
                        {
                            FruitID=0,
                            FruitName="",
                            HowToEat="",
                            Detail="",
                            ProductSeason=0,
                            PlaceID=0,
                            Enabled=true,
		
	                    };
        }
        public FruitsDTO GetDTOSeed()
        {
            return new FruitsDTO
                        {
                            FruitID=0,
                            FruitName="",
                            HowToEat="",
                            Detail="",
                            ProductSeason=0,
                            PlaceID=0,
                            Enabled=true,
		
	                    };
        }
    }
}
