// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class InventorySeed
	{		
  
        public T_Inventory GetEntitySeed()
        {
            return new T_Inventory
                        {
                            InventoryID=RandomData.GetRandomInt(1,100),
                            Count=RandomData.GetRandomInt(1,100),
                            FruitID=RandomData.GetRandomInt(1,100),
                            StorageID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
        public InventoryDTO GetDTOSeed()
        {
            return new InventoryDTO
                        {
                            InventoryID=RandomData.GetRandomInt(1,100),
                            Count=RandomData.GetRandomInt(1,100),
                            FruitID=RandomData.GetRandomInt(1,100),
                            StorageID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
    }
}
