// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class ManagerSeed
	{		
  
        public T_Manager GetEntitySeed()
        {
            return new T_Manager
                        {
                            ManagerID=RandomData.GetRandomInt(1,100),
                            LoginNum="",
                            PassWord="",
                            Enabled=true,
                            DateCreate=RandomData.GetRadomTime(),
		
	                    };
        }
        public ManagerDTO GetDTOSeed()
        {
            return new ManagerDTO
                        {
                            ManagerID=RandomData.GetRandomInt(1,100),
                            LoginNum="",
                            PassWord="",
                            Enabled=true,
                            DateCreate=RandomData.GetRadomTime(),
		
	                    };
        }
    }
}
