// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class ManagerPermissionSeed
	{		
  
        public T_ManagerPermission GetEntitySeed()
        {
            return new T_ManagerPermission
                        {
                            ManagerPermissionID=RandomData.GetRandomInt(1,100),
                            ManagerID=RandomData.GetRandomInt(1,100),
                            PermissionID=RandomData.GetRandomInt(1,100),
                            Enabled=true,
                            Permission=0,
		
	                    };
        }
        public ManagerPermissionDTO GetDTOSeed()
        {
            return new ManagerPermissionDTO
                        {
                            ManagerPermissionID=RandomData.GetRandomInt(1,100),
                            ManagerID=RandomData.GetRandomInt(1,100),
                            PermissionID=RandomData.GetRandomInt(1,100),
                            Enabled=true,
                            Permission=0,
		
	                    };
        }
    }
}
