// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class PermissionSeed
	{		
  
        public T_Permission GetEntitySeed()
        {
            return new T_Permission
                        {
                            PermissionID=RandomData.GetRandomInt(1,100),
                            PermissionName="",
                            PermissionNum="",
                            ParentNum="",
                            PermissionType=0,
                            PermissionUrl="",
                            PermissionAction="",
                            PermissionStyle="",
                            Enabled=true,
		
	                    };
        }
        public PermissionDTO GetDTOSeed()
        {
            return new PermissionDTO
                        {
                            PermissionID=RandomData.GetRandomInt(1,100),
                            PermissionName="",
                            PermissionNum="",
                            ParentNum="",
                            PermissionType=0,
                            PermissionUrl="",
                            PermissionAction="",
                            PermissionStyle="",
                            Enabled=true,
		
	                    };
        }
    }
}
