// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class PostAddressSeed
	{		
  
        public T_PostAddress GetEntitySeed()
        {
            return new T_PostAddress
                        {
                            PostAddressID=RandomData.GetRandomInt(1,100),
                            Address="",
                            IsDefault=true,
                            Phone="",
                            ContentName="",
                            Tel="",
                            Detail="",
                            UserID=RandomData.GetRandomInt(1,100),
                            PlaceID=RandomData.GetRandomInt(1,100),
                            Enabled=true,
		
	                    };
        }
        public PostAddressDTO GetDTOSeed()
        {
            return new PostAddressDTO
                        {
                            PostAddressID=RandomData.GetRandomInt(1,100),
                            Address="",
                            IsDefault=true,
                            Phone="",
                            ContentName="",
                            Tel="",
                            Detail="",
                            UserID=RandomData.GetRandomInt(1,100),
                            PlaceID=RandomData.GetRandomInt(1,100),
                            Enabled=true,
		
	                    };
        }
    }
}
