// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
namespace DataSeeds
{
	public class ProductsSeed
	{		
  
        public T_Products GetEntitySeed()
        {
            return new T_Products
                        {
                            ProductID=0,
                            OriginalPrice=0,
                            SalePrice=0,
                            SalesVolume=0,
                            Enabled=true,
		
	                    };
        }
        public ProductsDTO GetDTOSeed()
        {
            return new ProductsDTO
                        {
                            ProductID=0,
                            OriginalPrice=0,
                            SalePrice=0,
                            SalesVolume=0,
                            Enabled=true,
		
	                    };
        }
    }
}
