// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
namespace DataSeeds
{
	public class ProductFruitsSeed
	{		
  
        public C_ProductFruits GetEntitySeed()
        {
            return new C_ProductFruits
                        {
                            ProductFruitsID=0,
		
	                    };
        }
        public ProductFruitsDTO GetDTOSeed()
        {
            return new ProductFruitsDTO
                        {
                            ProductFruitsID=0,
		
	                    };
        }
    }
}
