// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class ProductOrdersSeed
	{		
  
        public T_ProductOrders GetEntitySeed()
        {
            return new T_ProductOrders
                        {
                            ProductOrdersID=RandomData.GetRandomInt(1,100),
                            Count=RandomData.GetRandomInt(1,100),
                            UserOrdersID=RandomData.GetRandomInt(1,100),
                            ProductID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
        public ProductOrdersDTO GetDTOSeed()
        {
            return new ProductOrdersDTO
                        {
                            ProductOrdersID=RandomData.GetRandomInt(1,100),
                            Count=RandomData.GetRandomInt(1,100),
                            UserOrdersID=RandomData.GetRandomInt(1,100),
                            ProductID=RandomData.GetRandomInt(1,100),
		
	                    };
        }
    }
}
