// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
namespace DataSeeds
{
	public class StockinSeed
	{		
  
        public T_Stockin GetEntitySeed()
        {
            return new T_Stockin
                        {
                            StockinID=0,
                            FruitID="",
                            count=0,
                            datecreate=DateTime.Now,
                            StorageID="",
                            PlaceID=0,
                            DeliverAddress="",
                            dateStockin=DateTime.Now,
                            status="",
                            SupplierID=null,
		
	                    };
        }
        public StockinDTO GetDTOSeed()
        {
            return new StockinDTO
                        {
                            StockinID=0,
                            FruitID="",
                            count=0,
                            datecreate=DateTime.Now,
                            StorageID="",
                            PlaceID=0,
                            DeliverAddress="",
                            dateStockin=DateTime.Now,
                            status="",
                            SupplierID=null,
		
	                    };
        }
    }
}
