// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Entities;
using DTO;
using Common;
namespace DataSeeds
{
	public class UserSeed
	{		
  
        public T_User GetEntitySeed()
        {
            return new T_User
                        {
                            UserID=RandomData.GetRandomInt(1,100),
                            UserName=RandomData.GetRandomName(),
                            Birthday=RandomData.GetRadomTime(),
                            Sex=0,
                            Email="",
                            LoginNum="",
                            PassWord="",
                            Phone="",
                            Enabled=true,
		
	                    };
        }
        public UserDTO GetDTOSeed()
        {
            return new UserDTO
                        {
                            UserID=RandomData.GetRandomInt(1,100),
                            UserName=RandomData.GetRandomName(),
                            Birthday=RandomData.GetRadomTime(),
                            Sex=0,
                            Email="",
                            LoginNum="",
                            PassWord="",
                            Phone="",
                            Enabled=true,
		
	                    };
        }
    }
}
