// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class FruitsDTO
	{		
		public int FruitID { get; set; }
		public string FruitName { get; set; }
		public string HowToEat { get; set; }
		public string Detail { get; set; }
		public byte ProductSeason { get; set; }
		public int PlaceID { get; set; }
		public bool Enabled { get; set; }
		
	}
}
