// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class InventoryDTO
	{		
		public int InventoryID { get; set; }
		public int Count { get; set; }
		public int FruitID { get; set; }
		public int StorageID { get; set; }
		
	}
}
