// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class ManagerDTO
	{		
		public int ManagerID { get; set; }
		public string LoginNum { get; set; }
		public string PassWord { get; set; }
		public bool Enabled { get; set; }
		public System.DateTime DateCreate { get; set; }
		
	}
}
