// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class ManagerPermissionDTO
	{		
		public int ManagerPermissionID { get; set; }
		public int ManagerID { get; set; }
		public int PermissionID { get; set; }
		public bool Enabled { get; set; }
		public byte Permission { get; set; }
		
	}
}
