// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class ProductsDTO
	{		
		public int ProductID { get; set; }
		public decimal OriginalPrice { get; set; }
		public decimal SalePrice { get; set; }
		public int SalesVolume { get; set; }
		public bool Enabled { get; set; }
		
	}
}
