// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class ProductPicDTO
	{		
		public int ProductPicID { get; set; }
		public string PicURL { get; set; }
		public string ThumbPicURL { get; set; }
		public System.DateTime DateCreate { get; set; }
		public int ProductID { get; set; }
		
	}
}
