// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class ProductOrdersDTO
	{		
		public int ProductOrdersID { get; set; }
		public int Count { get; set; }
		public int UserOrdersID { get; set; }
		public int ProductID { get; set; }
		
	}
}
