// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class SupplierDTO
	{		
		public int SupplierID { get; set; }
		public string Name { get; set; }
		public string Address { get; set; }
		public string Tel { get; set; }
		public string Phone { get; set; }
		public string Contacts { get; set; }
		public string Detail { get; set; }
		public bool Enabled { get; set; }
		public int PlaceID { get; set; }
		
	}
}
