// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class UserDTO
	{		
		public int UserID { get; set; }
		public string UserName { get; set; }
		public System.DateTime Birthday { get; set; }
		public byte Sex { get; set; }
		public string Email { get; set; }
		public string LoginNum { get; set; }
		public string PassWord { get; set; }
		public string Phone { get; set; }
		public bool Enabled { get; set; }
		
	}
}
