// <autogenerated>
//   This file was generated by T4 code generator EntitisBuild.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
namespace DTO
{
	public class UserOrdersDTO
	{		
		public int UserOrdersID { get; set; }
		public System.DateTime DateCreate { get; set; }
		public decimal Amount { get; set; }
		public decimal SaleAmount { get; set; }
		public byte OrderStatus { get; set; }
		public string LogisticsNum { get; set; }
		public System.DateTime DatePay { get; set; }
		public System.DateTime DateConfirm { get; set; }
		public int UserID { get; set; }
		public bool Enabled { get; set; }
		public decimal postage { get; set; }
		
	}
}
